"""News-threshold universe and headline/story queue helpers for the top-1k cache."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

PAPER_START = "2003-01-01"
PAPER_END = "2014-12-31"
PAPER_WEEKS = ((pd.Timestamp(PAPER_END) - pd.Timestamp(PAPER_START)).days + 1) / 7.0
MIN_USABLE_HEADLINES = 100
DEFAULT_UNIVERSE_CSV = "app_data/ravenpack_news_threshold_universe.csv"
DEFAULT_STORY_QUEUE = "app_data/story_pull_queue.txt"
STORY_QUEUE_HEADER = """# Full-story pull order under the shared LSEG ~10k/day Workspace cap.
# One ticker per line — the full RavenPack ≥1 article/week universe, volume-rank order.
# Cron skips names that still lack usable Refinitiv headlines (≥100 rows) until backfilled.
# Regenerated by scripts/build_news_threshold_universe.py --sync-story-queue.
"""


def parquet_row_count(path: Path) -> int:
    if not path.is_file():
        return 0
    try:
        import pyarrow.parquet as pq

        return int(pq.read_metadata(path).num_rows)
    except Exception:
        try:
            return int(len(pd.read_parquet(path, columns=[])))
        except Exception:
            return 0


def iter_ticker_cache_dirs(by_ticker_dir: Path) -> list[Path]:
    if not by_ticker_dir.is_dir():
        return []
    return sorted(path for path in by_ticker_dir.glob("rank_*") if path.is_dir())


def _provider_status_map(manifest: dict) -> dict[str, str]:
    out: dict[str, str] = {}
    for row in manifest.get("provider_status") or []:
        name = str(row.get("provider") or "").strip().lower()
        if name:
            out[name] = str(row.get("status") or "")
    return out


def scan_batch_ticker_coverage(by_ticker_dir: Path) -> pd.DataFrame:
    """One row per top-1k cache dir with RavenPack + Refinitiv headline counts."""
    rows: list[dict[str, object]] = []
    for cache_dir in iter_ticker_cache_dirs(by_ticker_dir):
        manifest_path = cache_dir / "manifest.json"
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            manifest = {}
        providers = _provider_status_map(manifest)
        ravenpack_path = cache_dir / "ravenpack_articles.parquet"
        news_path = cache_dir / "refinitiv_news.parquet"
        ravenpack_rows = parquet_row_count(ravenpack_path)
        headline_rows = parquet_row_count(news_path)
        avg_week = ravenpack_rows / PAPER_WEEKS if ravenpack_rows else 0.0
        ticker = str(manifest.get("ticker") or cache_dir.name.split("_", 2)[-1]).upper()
        rows.append(
            {
                "volume_rank": manifest.get("volume_rank"),
                "permno": manifest.get("permno"),
                "ticker": ticker,
                "company_name": manifest.get("company_name") or "",
                "batch_status": manifest.get("status") or "",
                "cache_dir": str(cache_dir),
                "wrds_ok": providers.get("wrds") == "ok",
                "yahoo_ok": providers.get("yahoo") == "ok",
                "ravenpack_ok": providers.get("ravenpack") == "ok" or ravenpack_rows > 0,
                "refinitiv_ok": providers.get("refinitiv") == "ok",
                "ravenpack_rows": int(ravenpack_rows),
                "avg_articles_per_week": round(float(avg_week), 4),
                "passes_weekly_threshold": bool(avg_week >= 1.0),
                "refinitiv_headline_rows": int(headline_rows),
                "has_usable_refinitiv_headlines": bool(headline_rows >= MIN_USABLE_HEADLINES),
            }
        )
    if not rows:
        return pd.DataFrame()
    frame = pd.DataFrame(rows)
    frame["volume_rank"] = pd.to_numeric(frame["volume_rank"], errors="coerce")
    return frame.sort_values(["volume_rank", "ticker"], na_position="last").reset_index(drop=True)


def news_threshold_universe(
    coverage: pd.DataFrame,
    *,
    min_avg_per_week: float = 1.0,
) -> pd.DataFrame:
    if coverage.empty:
        return coverage
    mask = coverage["ravenpack_rows"].fillna(0).astype(int).gt(0) & (
        coverage["avg_articles_per_week"].fillna(0) >= float(min_avg_per_week)
    )
    return coverage.loc[mask].copy().reset_index(drop=True)


def headline_counts_by_ticker(coverage: pd.DataFrame) -> dict[str, int]:
    counts: dict[str, int] = {}
    if coverage.empty:
        return counts
    for _, row in coverage.iterrows():
        ticker = str(row.get("ticker") or "").upper().strip()
        if not ticker:
            continue
        n = int(row.get("refinitiv_headline_rows") or 0)
        counts[ticker] = max(n, counts.get(ticker, 0))
    return counts


def ordered_story_queue_tickers(
    headline_rows_by_ticker: dict[str, int],
    *,
    min_headlines: int = MIN_USABLE_HEADLINES,
    prefer_first: tuple[str, ...] = ("MSFT",),
) -> list[str]:
    """Ready-only queue (tickers that already have usable headline caches)."""
    usable = {
        ticker.upper(): int(rows)
        for ticker, rows in headline_rows_by_ticker.items()
        if int(rows) >= int(min_headlines)
    }
    preferred = [ticker for ticker in prefer_first if ticker in usable]
    rest = sorted(
        (ticker for ticker in usable if ticker not in preferred),
        key=lambda ticker: (-usable[ticker], ticker),
    )
    return [*preferred, *rest]


def ordered_universe_story_queue(
    universe: pd.DataFrame,
    *,
    prefer_first: tuple[str, ...] = ("MSFT",),
) -> list[str]:
    """Full news-threshold universe in volume-rank order (ready + waiting on headlines)."""
    if universe is None or getattr(universe, "empty", True) or "ticker" not in universe.columns:
        return []
    frame = universe.copy()
    frame["ticker"] = frame["ticker"].astype(str).str.upper().str.strip()
    frame = frame.loc[frame["ticker"].astype(bool)]
    if "volume_rank" in frame.columns:
        frame = frame.sort_values(["volume_rank", "ticker"], na_position="last")
    else:
        frame = frame.sort_values(["ticker"])
    ordered = list(dict.fromkeys(frame["ticker"].tolist()))
    preferred = [ticker for ticker in prefer_first if ticker in ordered]
    rest = [ticker for ticker in ordered if ticker not in preferred]
    return [*preferred, *rest]


def render_story_queue(tickers: list[str], *, header: str = STORY_QUEUE_HEADER) -> str:
    body = "\n".join(str(ticker).upper().strip() for ticker in tickers if str(ticker).strip())
    return f"{header.rstrip()}\n{body}\n"


def tickers_needing_headline_backfill(
    coverage: pd.DataFrame,
    *,
    universe_only: bool = True,
    min_headlines: int = MIN_USABLE_HEADLINES,
) -> pd.DataFrame:
    if coverage.empty:
        return coverage
    frame = news_threshold_universe(coverage) if universe_only else coverage.copy()
    if frame.empty:
        return frame
    needed = frame.loc[frame["refinitiv_headline_rows"].fillna(0).astype(int) < int(min_headlines)]
    return needed.sort_values(["volume_rank", "ticker"], na_position="last").reset_index(drop=True)


def write_news_threshold_universe(
    by_ticker_dir: Path,
    dest: Path,
    *,
    min_avg_per_week: float = 1.0,
) -> pd.DataFrame:
    coverage = scan_batch_ticker_coverage(by_ticker_dir)
    universe = news_threshold_universe(coverage, min_avg_per_week=min_avg_per_week)
    dest.parent.mkdir(parents=True, exist_ok=True)
    universe.to_csv(dest, index=False)
    return universe


def sync_story_queue_file(
    queue_path: Path,
    headline_rows_by_ticker: dict[str, int] | None = None,
    *,
    universe: pd.DataFrame | None = None,
    prefer_first: tuple[str, ...] = ("MSFT",),
    ready_only: bool = False,
) -> list[str]:
    """Write the story pull queue.

    Default is the **full** news-threshold universe (volume-rank order). Pass
    ``ready_only=True`` to keep only tickers with usable headlines.
    """
    if ready_only or universe is None or getattr(universe, "empty", True):
        tickers = ordered_story_queue_tickers(
            headline_rows_by_ticker or {},
            prefer_first=prefer_first,
        )
    else:
        tickers = ordered_universe_story_queue(universe, prefer_first=prefer_first)
    queue_path.parent.mkdir(parents=True, exist_ok=True)
    queue_path.write_text(render_story_queue(tickers), encoding="utf-8")
    return tickers
