"""Model training and inference for news-sentiment classification."""

from sentiment_ltr.models.phrasebank_sentiment import (
    DEFAULT_MODEL_DIR,
    MAX_LENGTH,
    MODEL_NAME,
    label_maps,
    load_classifier,
    load_metrics,
    load_phrasebank,
    model_is_saved,
    phrasebank_data_provenance,
    phrasebank_probability_chart_frame,
    phrasebank_sample_inference_frame,
    phrasebank_tokenization_example_frame,
    phrasebank_tokenizer_settings_frame,
    predict_sentences,
)
from sentiment_ltr.models.ravenpack_sentiment import (
    DEFAULT_RAVENPACK_MODEL_DIR,
    ID2LABEL,
    RAVENPACK_NEWS_DIR,
    SENTIMENT_SCORE_THRESHOLD,
    SPLIT_SOURCE,
    assign_time_split,
    discover_ravenpack_article_files,
    load_ravenpack_labeled_frame,
    ravenpack_class_balance,
    ravenpack_data_provenance,
    ravenpack_model_is_saved,
    ravenpack_split_summary,
    ravenpack_to_hf_dataset,
    validate_phrasebank_ravenpack_label_alignment,
)

__all__ = [
    # phrasebank_sentiment
    "DEFAULT_MODEL_DIR",
    "MAX_LENGTH",
    "MODEL_NAME",
    "label_maps",
    "load_classifier",
    "load_metrics",
    "load_phrasebank",
    "model_is_saved",
    "phrasebank_data_provenance",
    "phrasebank_probability_chart_frame",
    "phrasebank_sample_inference_frame",
    "phrasebank_tokenization_example_frame",
    "phrasebank_tokenizer_settings_frame",
    "predict_sentences",
    # ravenpack_sentiment
    "DEFAULT_RAVENPACK_MODEL_DIR",
    "ID2LABEL",
    "RAVENPACK_NEWS_DIR",
    "SENTIMENT_SCORE_THRESHOLD",
    "SPLIT_SOURCE",
    "assign_time_split",
    "discover_ravenpack_article_files",
    "load_ravenpack_labeled_frame",
    "ravenpack_class_balance",
    "ravenpack_data_provenance",
    "ravenpack_model_is_saved",
    "ravenpack_split_summary",
    "ravenpack_to_hf_dataset",
    "validate_phrasebank_ravenpack_label_alignment",
]
